[163] Changelog:
Changed:

- added additional hub command
- updated setup command

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -3,17 +3,52 @@
 export PROJECT_ROOT
 PROJECT_ROOT="$(dirname "$(realpath $0)")/../"
 USE_DOCKER=0
+MANAGER_CLI="${PROJECT_ROOT}/server-manager"
 
-# Validate is docker installed and run
-function _installDocker() {
+_output() {
+    style_start=""
+    style_end=""
+    if [ "${2:-}" != "" ]; then
+    case $2 in
+        "success")
+            style_start="\033[0;32m"
+            style_end="\033[0m"
+            ;;
+        "error")
+            style_start="\033[31;31m"
+            style_end="\033[0m"
+            ;;
+        "info"|"warning")
+            style_start="\033[33m"
+            style_end="\033[39m"
+            ;;
+        "heading")
+            style_start="\033[1;33m"
+            style_end="\033[22;39m"
+            ;;
+        "comment")
+            style_start="\033[2m"
+            style_end="\033[22;39m"
+            ;;
+    esac
+    fi
+
+    builtin echo -e "${style_start}${1}${style_end}"
+}
+
+# Validate is docker installed
+# Install in case required
+_installDocker() {
     if [ ! -x "$(command -v docker)" ]; then
         read -r -p "Did Docker get installed! Do you want to proceed? (Y/N) " yn
         case $yn in
             [Yy]* )
-                "${PROJECT_ROOT}"/bin/docker/install.sh ;;
+                "${PROJECT_ROOT}"/bin/docker/install.sh
+                ;;
             [Nn]* )
                 echo "Installation process stopped...";
-                exit;;
+                exit
+                ;;
         esac
     fi
 
@@ -40,8 +75,52 @@ function _installDocker() {
     fi
 }
 
+# Check docker ports
+_checkDockerPorts() {
+    if lsof -i -P -n | grep LISTEN | grep :80
+    then
+        _output "  [ ] ERROR: The port 80 is already used by another service" "error"
+    fi
+
+    if lsof -i -P -n | grep LISTEN | grep :443
+    then
+        _output "  [ ] ERROR: The port 80 is already used by another service" "error"
+    fi
+}
+
+# Check is all required applications are installed
+_checkRequiredLibs() {
+    if command -v composer >/dev/null 2>&1; then
+        _output "  [*] Composer is installed" "success"
+    else
+        _output "  [ ] ERROR: Composer is required for installation" "error"
+        exit 1
+    fi
+
+    if command -v php >/dev/null 2>&1; then
+        _output "  [*] PHP is installed" "success"
+    else
+        _output "  [ ] ERROR: PHP is required for installation" "error"
+        exit 1
+    fi
+
+    if command -v zip >/dev/null 2>&1; then
+        _output "  [*] Zip is installed" "success"
+    else
+        _output "  [ ] ERROR: Zip is required for installation" "error"
+        exit 1
+    fi
+
+    if command -v curl >/dev/null 2>&1; then
+        _output "  [*] CURL is installed" "success"
+    else
+        _output "  [ ] ERROR: CURL is required for installation" "error"
+        exit 1
+    fi
+}
+
 # Replace Function
-function _replace_pattern () {
+_replace_pattern () {
     local FROM=$1
     local TO=$2
     local FILE=$3
@@ -54,11 +133,19 @@ function _replace_pattern () {
 }
 
 # Generate JWT secret key
-function _generateJwtKey() {
+_generateJwtKey() {
     local jwt_secret
     jwt_secret=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 43)
 
     echo "$jwt_secret"
+}
+
+_setCliLocation() {
+    CLI_LOC=/usr/bin/server-manager
+
+    if [ -n "${SM_INSTALL_CLIPATH}" ]; then
+        CLI_LOC="${SM_INSTALL_CLIPATH}"
+    fi
 }
 
 echo "Started Project setting"
@@ -68,8 +155,11 @@ read -r -p "Do you want to use a docker? (Y/N) " yn
 case $yn in
     [Yy]* )
         USE_DOCKER=1
-        _installDocker ;;
+        _checkDockerPorts
+        _installDocker
+        ;;
     [Nn]* )
+        _checkRequiredLibs
         ;;
 esac
 
@@ -78,20 +168,19 @@ echo "Initializing Base configurations"
 if [ ! -f ${PROJECT_ROOT}/.env ]; then
     cp ${PROJECT_ROOT}/env-sample ${PROJECT_ROOT}/.env
 
-    # Get Service URL
-    read -rp "Enter the host name for the Service:" APP_SERVICE_URL
-    _replace_pattern "APP_SERVICE_URL=" "APP_SERVICE_URL=${APP_SERVICE_URL}" ${PROJECT_ROOT}/.env
+    _replace_pattern "APP_DOCKER_USE=1" "APP_DOCKER_USE=${USE_DOCKER}" ${PROJECT_ROOT}/.env
 
     # Get Server URL
     if [ $USE_DOCKER == 1 ]; then
-        read -rp "Enter the host name for the Server:" APP_DOCKER_SERVER_URL
+        read -rp "Enter the host name for the current Server ( example.com ): " APP_DOCKER_SERVER_URL
         _replace_pattern "APP_DOCKER_SERVER_URL=" "APP_DOCKER_SERVER_URL=${APP_DOCKER_SERVER_URL}" ${PROJECT_ROOT}/.env
     fi
 
     # Get path to dumps folder
-    APP_DUMP_PATH=''
+    APP_DUMP_PATH=""
     while [[ ${APP_DUMP_PATH} == '' || "${APP_DUMP_PATH}" =~ "~" ]]; do
-        read -rp "Enter the full the path to folder with dumps:" APP_DUMP_PATH
+        read -rp "Enter the full the path to folder with dumps (default: "${HOME}/backups/" ): " APP_DUMP_PATH
+        APP_DUMP_PATH=${APP_DUMP_PATH:="${HOME}/backups/"}
         if [ "${APP_DUMP_PATH::1}" != "/" ]; then
             APP_DUMP_PATH="/${APP_DUMP_PATH}"
         fi
@@ -100,6 +189,7 @@ if [ ! -f ${PROJECT_ROOT}/.env ]; then
             APP_DUMP_PATH="${APP_DUMP_PATH}/"
         fi
     done
+
     _replace_pattern "APP_DUMP_PATH=''" "APP_DUMP_PATH='${APP_DUMP_PATH}'" ${PROJECT_ROOT}.env
     _replace_pattern "APP_DOCKER_PATH_DUMP=''" "APP_DOCKER_PATH_DUMP='${APP_DUMP_PATH}dumps'" ${PROJECT_ROOT}.env
     _replace_pattern "APP_DOCKER_PATH_CONFIG=''" "APP_DOCKER_PATH_CONFIG='${APP_DUMP_PATH}config'" ${PROJECT_ROOT}.env
@@ -110,18 +200,20 @@ fi
 
 # Select engines:
 echo "Initializing supported DB engines"
-options=("MySQL" "Postgres" "Continue")
+options=("MySQL" "Postgres" "Next Steps")
 select option in "${options[@]}"; do
     case $REPLY in
         1)
             if [ ! -f ${PROJECT_ROOT}/.env.mysql ]; then
                 cp ${PROJECT_ROOT}/env.mysql-sample ${PROJECT_ROOT}/.env.mysql
             fi
+            echo "MySQL Selected."
             ;;
         2)
             if [ ! -f {PROJECT_ROOT}/.env.postgres ]; then
                 cp ${PROJECT_ROOT}/env.postgres-sample ${PROJECT_ROOT}/.env.postgres
             fi
+            echo "Postgres Selected."
             ;;
         3)
             break
@@ -158,4 +250,17 @@ else
     fi
 
     php "${PROJECT_ROOT}"bin/console app:server:add
+fi
+
+_setCliLocation
+
+if rm -f "${CLI_LOC}"; then
+    if cp -f "${MANAGER_CLI}" "${CLI_LOC}"; then
+        chmod 755 "${CLI_LOC}"
+        echo "cli installed"
+    else
+        echo "failed to copy new cli into place"
+    fi
+else
+    echo "could not remove existing cli"
 fi
